sudo: false

os:
  - osx
  - linux

node_js:
 - "8"


before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - unset _JAVA_OPTIONS


install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent

cache: 
  directories:
    - node_modules